// Separate Playwright config for the one production-build PWA spec
// (e2e/pwa.spec.ts) — PLAN.md §9/§11 Phase 6. vite-plugin-pwa's manifest +
// service worker are only generated by `vite build` (generateSW mode), not
// Vite's dev server, so this spec needs a real `npm run build && npm start`
// boot rather than the dev-mode `npm run dev` webServer
// e2e/playwright.config.ts's other 10 specs share. Kept as a fully separate
// config (not a second project in the main config) so the two suites never
// share a webServer or port-reuse assumption, and so `npm run e2e` (dev
// mode, 10 specs) is completely unaffected by this one — run this suite
// explicitly via `npm run e2e:prod`.
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { defineConfig, devices } from '@playwright/test';

const REPO_ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const PORT = 4680;
const BASE_URL = `http://localhost:${PORT}`;

export default defineConfig({
  testDir: '.',
  testMatch: /pwa\.spec\.ts$/,
  outputDir: path.join(REPO_ROOT, 'e2e', 'test-results-prod'),
  fullyParallel: false,
  workers: 1,
  retries: 0,
  reporter: 'list',
  use: {
    baseURL: BASE_URL,
    trace: 'retain-on-failure',
  },
  projects: [
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'] },
    },
  ],
  webServer: {
    // Build first (so web/dist + its precache manifest actually exist),
    // then boot the production server, which statically serves web/dist
    // (server/src/static.ts) with zero separate Vite dev server.
    command: 'npm run build && npm start',
    cwd: REPO_ROOT,
    url: BASE_URL,
    reuseExistingServer: !process.env.CI,
    timeout: 120_000,
  },
});
